on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - '**.ts'
      - '**.tsx'
      - 'yarn.lock'
      - 'games.json'
      - 'package.json'

name: Deploy to Github-Pages
jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: ğŸ“¦ Checkout
        uses: actions/checkout@v4.0.0

      - name: ğŸš§ Setup Node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18.13.0

      - name: ğŸ¤– Setup Project
        run: 'yarn'

      - name: ğŸŒ Fetch
        run: 'STEAMGRIDDB_KEY=${{ secrets.STEAMGRIDDB_KEY }} yarn prefetch'

      - name: ğŸ‘· Build
        run: |
          GITHUB_ACTIONS=1 yarn build
          yarn export
          touch out/.nojekyll

      - name: ğŸ‰ Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./out
          keep_files: true
